### ISSUE TITLE
[Question] Is this project updated regularly?

### ISSUE THREAD

**Issue by iceleo-com** [bigcommerce/checkout-js#854]
Hi,

Hope you are doing well.
I'm an engineer at fabricwarehouse.com (one of your clients). For many reasons, we want to use this code as our main checkout app instead of the default checkout app.

Our question: Is this project updated regularly following the BigCommerce system's update? Is it fully tested?

Currently, we only use PayPal as a payment method.

Thank you!

**Comment by animesh1987** [comment]
Hi @iceleo-com from what I can see fabricwarehouse.com uses the native checkout. Is that correct? 

Are you planning to change that to a custom checkout?

The project is regularly updated and maintained. The project has very good amount of testing in form of unit tests and we do run functional tests as part of the release pipeline.

**Comment by animesh1987** [comment]
Also can take a look at the commit history to see the activity on the project https://github.com/bigcommerce/checkout-js/commits/master

**Comment by bc-peng** [comment]
Hello, we release almost every working day. You can tell by looking at our release history. All BC customers will receive the new release in about three business days. In response to another question, we have 1400+ unit tests in this repo.

We also keep an eye out for new issues in this repo.

**Comment by TomA-R** [comment]
Hi @iceleo-com!

This _is_ the default BigCommerce ("optimized one-page") checkout. Any changes made to this repository are applied to most BigCommerce stores (as long as they're on Optimized One-Page checkout, so not custom/multi-page/other checkouts), during a staggered rollout.

You're welcome to fork this code since it is open source, so you can create your own custom checkout. Keep in mind that it's up to you to update it. New functionality and security updates may not automatically work or be included on forked checkouts, since the old version may not have the required code for support this. We do aim to be as backwards-compatible as possible, so new changes of storefront APIs (which this repo - through [the checkout-sdk-js](https://github.com/bigcommerce/checkout-sdk-js) uses) _shouldn't_ break old versions of the checkout (so most custom checkouts).

Test coverage is on the unit test level in this repository. As a final check before deploying this to BigCommerce stores, we run many high-level (acceptance, functional, and contract) tests internally before deploying this to BigCommerce stores. People using this repository to create their own custom checkout can write their own high-level tests, which could perhaps run on their sandbox (or dev store) before deploying their version to their production store.

We're always interested in why people are building their own checkouts! Do you have particular requirements the default checkout doesn't cater for?

**Comment by iceleo-com** [comment]
@animesh1987 , @bc-peng thank you so much for the clarification! I will close this question

@TomA-R oh yes, we need some custom to make it smarter, and easier to use for our customers
